import { db, q, qi, tx, isPg, columnsOf, tableExists } from './db'
import { ENTITY_LIST } from '../shared/entities'
import type { EntityDef, FieldDef } from '../shared/types'
import { nowIso } from './util'

const MIGRATIONS: { id: string; sql: string }[] = [
  {
    id: '001_system_tables',
    sql: `
    CREATE TABLE sessions (
      id TEXT PRIMARY KEY, user_id INTEGER NOT NULL, created_at TEXT NOT NULL, expires_at TEXT NOT NULL, last_seen TEXT NOT NULL, ip TEXT, user_agent TEXT
    );
    CREATE INDEX ix_sessions_user ON sessions(user_id);
    CREATE TABLE audit_log (
      id INTEGER PRIMARY KEY AUTOINCREMENT, at TEXT NOT NULL, user_id INTEGER, user_name TEXT, entity TEXT NOT NULL, record_id INTEGER, record_label TEXT,
      action TEXT NOT NULL, changes TEXT, ip TEXT
    );
    CREATE INDEX ix_audit_entity ON audit_log(entity, record_id);
    CREATE INDEX ix_audit_at ON audit_log(at);
    CREATE TABLE login_events (
      id INTEGER PRIMARY KEY AUTOINCREMENT, at TEXT NOT NULL, email TEXT, user_id INTEGER, success INTEGER NOT NULL, reason TEXT, ip TEXT, user_agent TEXT
    );
    CREATE TABLE notifications (
      id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, kind TEXT NOT NULL DEFAULT 'info', title TEXT NOT NULL, body TEXT, link TEXT,
      read_at TEXT, created_at TEXT NOT NULL, dedupe_key TEXT
    );
    CREATE INDEX ix_notif_user ON notifications(user_id, read_at);
    CREATE UNIQUE INDEX ux_notif_dedupe ON notifications(user_id, dedupe_key) WHERE dedupe_key IS NOT NULL;
    CREATE TABLE comments (
      id INTEGER PRIMARY KEY AUTOINCREMENT, entity TEXT NOT NULL, record_id INTEGER NOT NULL, user_id INTEGER NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL, deleted_at TEXT
    );
    CREATE INDEX ix_comments_rec ON comments(entity, record_id);
    CREATE TABLE record_refs (
      id INTEGER PRIMARY KEY AUTOINCREMENT, entity TEXT NOT NULL, record_id INTEGER NOT NULL, ref_type TEXT NOT NULL, ref_value TEXT NOT NULL, note TEXT, created_by INTEGER, created_at TEXT NOT NULL
    );
    CREATE INDEX ix_refs_rec ON record_refs(entity, record_id);
    CREATE INDEX ix_refs_val ON record_refs(ref_value);
    CREATE TABLE record_tags (
      id INTEGER PRIMARY KEY AUTOINCREMENT, entity TEXT NOT NULL, record_id INTEGER NOT NULL, tag TEXT NOT NULL, created_by INTEGER, created_at TEXT NOT NULL,
      UNIQUE(entity, record_id, tag)
    );
    CREATE TABLE record_links (
      id INTEGER PRIMARY KEY AUTOINCREMENT, entity TEXT NOT NULL, record_id INTEGER NOT NULL, to_entity TEXT NOT NULL, to_id INTEGER NOT NULL, note TEXT, created_by INTEGER, created_at TEXT NOT NULL,
      UNIQUE(entity, record_id, to_entity, to_id)
    );
    CREATE TABLE record_likes (
      entity TEXT NOT NULL, record_id INTEGER NOT NULL, user_id INTEGER NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(entity, record_id, user_id)
    );
    CREATE TABLE video_calls (
      id INTEGER PRIMARY KEY AUTOINCREMENT, entity TEXT NOT NULL, record_id INTEGER NOT NULL, room TEXT NOT NULL, url TEXT NOT NULL, created_by INTEGER, created_at TEXT NOT NULL
    );
    CREATE INDEX ix_video_rec ON video_calls(entity, record_id);
    CREATE TABLE settings ( key TEXT PRIMARY KEY, value TEXT, updated_at TEXT );
    CREATE TABLE sequences ( key TEXT PRIMARY KEY, value INTEGER NOT NULL );
    CREATE TABLE webhook_deliveries (
      id INTEGER PRIMARY KEY AUTOINCREMENT, webhook_id INTEGER NOT NULL, event TEXT NOT NULL, status INTEGER, ok INTEGER, response TEXT, at TEXT NOT NULL
    );
    CREATE TABLE job_tracking_tokens ( job_id INTEGER PRIMARY KEY, token TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL );
    `,
  },
]

/** System-table DDL is written once in SQLite dialect and adapted for PostgreSQL. */
const ddl = (sql: string) => (isPg
  ? sql.replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g, 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY').replace(/\bINTEGER\b/g, 'BIGINT').replace(/\bREAL\b/g, 'DOUBLE PRECISION')
  : sql)
/** SQLite's ROUND() accepts floats; PostgreSQL's only accepts numeric. This keeps the ~70 ROUND() calls in reports working unchanged. */
const PG_COMPAT = `CREATE OR REPLACE FUNCTION round(double precision, integer) RETURNS double precision LANGUAGE sql IMMUTABLE AS 'SELECT round($1::numeric, $2)::double precision'`

const colType = (f: FieldDef): string => {
  switch (f.type) {
    case 'int': case 'ref': case 'bool': case 'money': return isPg ? 'BIGINT' : 'INTEGER'
    case 'number': case 'percent': return isPg ? 'DOUBLE PRECISION' : 'REAL'
    default: return 'TEXT'
  }
}
const storedFields = (def: EntityDef) => def.fields.filter(f => !f.virtual)

export function syncSchema() {
  if (isPg) db.exec(PG_COMPAT)
  db.exec(`CREATE TABLE IF NOT EXISTS schema_migrations (id TEXT PRIMARY KEY, applied_at TEXT NOT NULL)`)
  const done = new Set(q.all<{ id: string }>('SELECT id FROM schema_migrations').map(r => r.id))
  for (const m of MIGRATIONS) {
    if (done.has(m.id)) continue
    tx(() => { db.exec(ddl(m.sql)); q.run('INSERT INTO schema_migrations(id, applied_at) VALUES (?, ?)', m.id, nowIso()) })
  }
  tx(() => { for (const def of ENTITY_LIST) syncEntity(def) })
}

function syncEntity(def: EntityDef) {
  const t = def.key
  const exists = tableExists(t)
  const fields = storedFields(def)
  if (!exists) {
    const cols = fields.map(f => `${qi(f.name)} ${colType(f)}`)
    db.exec(`CREATE TABLE ${qi(t)} (
      id ${isPg ? 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT'},
      ${cols.join(',\n      ')}${cols.length ? ',' : ''}
      custom TEXT,
      version ${isPg ? 'BIGINT' : 'INTEGER'} NOT NULL DEFAULT 1,
      created_at TEXT NOT NULL, updated_at TEXT NOT NULL, created_by ${isPg ? 'BIGINT' : 'INTEGER'}, updated_by ${isPg ? 'BIGINT' : 'INTEGER'}, deleted_at TEXT
    )`)
  } else {
    const have = new Set(columnsOf(t).map(c => c.name))
    for (const f of fields) if (!have.has(f.name)) db.exec(`ALTER TABLE ${qi(t)} ADD COLUMN ${qi(f.name)} ${colType(f)}`)
  }
  for (const f of fields) {
    if (f.unique) db.exec(`CREATE UNIQUE INDEX IF NOT EXISTS ${qi(`ux_${t}_${f.name}`)} ON ${qi(t)}(${qi(f.name)}) WHERE deleted_at IS NULL AND ${qi(f.name)} IS NOT NULL AND ${qi(f.name)} <> ''`)
    else if (f.type === 'ref' || f.name === def.statusField || f.search || (f.type === 'date' && f.list)) db.exec(`CREATE INDEX IF NOT EXISTS ${qi(`ix_${t}_${f.name}`)} ON ${qi(t)}(${qi(f.name)})`)
  }
  db.exec(`CREATE INDEX IF NOT EXISTS ${qi(`ix_${t}_deleted`)} ON ${qi(t)}(deleted_at)`)
}
