// Shared metadata types. A single entity definition drives the database schema,
// the REST API validation, the list/form UI, CSV import/export and permissions.

export type FieldType =
  | 'text' | 'textarea' | 'int' | 'number' | 'money' | 'percent'
  | 'date' | 'datetime' | 'select' | 'bool' | 'email' | 'phone' | 'url' | 'ref' | 'json'

export interface Option { value: string; label?: string; color?: string }

export interface FieldDef {
  name: string
  label: string
  type: FieldType
  required?: boolean
  unique?: boolean
  options?: (string | Option)[]
  /** target entity key for type 'ref' */
  ref?: string
  /** static filter applied to the ref picker, e.g. { is_customer: 1 } */
  refFilter?: Record<string, string | number>
  default?: string | number | boolean | null
  /** form section heading */
  section?: string
  /** show as a column in list views */
  list?: boolean
  readonly?: boolean
  /** hide from forms (still stored / returned) */
  hidden?: boolean
  /** never returned by the API and never writable through it */
  secret?: boolean
  /** not stored; handled by hooks (e.g. password) */
  virtual?: boolean
  help?: string
  placeholder?: string
  /** included in free-text search */
  search?: boolean
  /** grid span 1..3 on the form */
  span?: 1 | 2 | 3
  min?: number
  max?: number
  /** server-computed – read-only on forms */
  computed?: boolean
  /** show in compact "key facts" strip on record pages */
  key?: boolean
}

export interface ChildDef {
  key: string
  label: string
  /** child entity key */
  entity: string
  /** column on the child that stores the parent id */
  fk: string
  /** field names (in order) shown in the inline editor; defaults to all non-hidden */
  columns?: string[]
  /** hide the add / remove controls (rows generated by the server) */
  fixed?: boolean
}

export interface EntityDef {
  key: string
  label: string
  plural: string
  /** permission module */
  module: string
  icon: string
  fields: FieldDef[]
  /** field names forming the display label of a record */
  title: string[]
  titleSep?: string
  /** template such as '{code}-{name}/{country_id}' (overrides title/titleSep) */
  titleFmt?: string
  titleUpper?: boolean
  /** auto-numbering */
  numbering?: { field: string; pattern: string }
  statusField?: string
  children?: ChildDef[]
  /** child entity: edited through its parent only */
  child?: boolean
  /** comments / follow ups / attachments / history side panel */
  panel?: boolean
  kanban?: { field: string }
  defaultSort?: { field: string; dir: 'asc' | 'desc' }
  /** records can never be deleted through the API (use void / status) */
  noDelete?: boolean
  /** read only through the generic API (rows are produced by server logic) */
  readonlyApi?: boolean
  /** field used for calendar placement */
  calendar?: { field: string; titleFrom?: string[] }
  /** print template key */
  print?: string
  /** hide from navigation */
  hidden?: boolean
  /** supports admin-defined custom fields */
  customFields?: boolean
  description?: string
}

export interface NavItem { label: string; to: string; icon: string; module?: string; entity?: string }
export interface NavGroup { label: string; icon: string; items: NavItem[] }

export const ACTIONS = ['view', 'create', 'edit', 'delete', 'approve', 'export'] as const
export type Action = typeof ACTIONS[number]

export interface ModuleDef { key: string; label: string; actions: Action[] }

export function optValue(o: string | Option): string { return typeof o === 'string' ? o : o.value }
export function optLabel(o: string | Option): string { return typeof o === 'string' ? o : (o.label ?? o.value) }

/** Compose a display label from a record following the entity title spec. */
export function recordTitle(def: EntityDef, rec: Record<string, any> | null | undefined, labels?: Record<string, string>): string {
  if (!rec) return ''
  if (def.titleFmt) {
    const out = def.titleFmt.replace(/\{(\w+)\}/g, (_m, n) => {
      const f = def.fields.find(x => x.name === n)
      const v = f?.type === 'ref' ? labels?.[n] : rec[n]
      return v === null || v === undefined ? '' : String(v)
    }).replace(/^[-/ ]+|[-/ ]+$/g, '').replace(/\/+$/, '')
    return def.titleUpper ? out.toUpperCase() : out
  }
  const parts = def.title
    .map(n => {
      const f = def.fields.find(x => x.name === n)
      if (f?.type === 'ref') return labels?.[n] ?? ''
      return rec[n]
    })
    .filter(v => v !== null && v !== undefined && v !== '')
  return parts.join(def.titleSep ?? ' · ') || `#${rec.id ?? ''}`
}
