#!/usr/bin/env python3
"""Generate docs/API.md from the route files + CRUD registry so the reference cannot drift from the code."""
import json, re, subprocess, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
mounts = {
 'authRouter':'/api/auth','shipmentsRouter':'/api/shipments','quotesRouter':'/api/quotes','invoicesRouter':'/api/invoices','accountingRouter':'/api/accounting','customsRouter':'/api/customs',
 'dispatchRouter':'/api/dispatch','driverRouter':'/api/driver','warehouseRouter':'/api/warehouse','procurementRouter':'/api/procurement','approvalsRouter':'/api/approvals','pipelineRouter':'/api/pipeline',
 'peopleRouter':'/api/hr','payrollRouter':'/api/payroll','complianceRouter':'/api/compliance','documentsRouter':'/api/documents','docintelRouter':'/api/docintel','inboxRouter':'/api/inbox',
 'webhooksRouter':'/api/webhooks','dashboardRouter':'/api/dashboard','aiRouter':'/api/ai','reportsRouter':'/api/reports','searchRouter':'/api/search','notificationsRouter':'/api/notifications',
 'portalRouter':'/api/portal','publicRouter':'/api/public','adminRouter':'/api/admin','lookupRouter':'/api/lookup',
}
public = {'authRouter','webhooksRouter','publicRouter'}
rows = []
pat = re.compile(r"(\w+Router)\.(get|post|put|patch|delete)\(\s*\n?\s*'([^']*)'(.{0,400})", re.S)
for f in sorted((root/'apps/api/src/routes').glob('*.ts')):
    src = f.read_text()
    for m in pat.finditer(src):
        var, method, path, tail = m.groups()
        if var not in mounts: continue
        head = tail.split('wrap(')[0]
        perms = re.findall(r"requirePerm\('(\w+)',\s*'(\w)'\)", head)
        auth = 'public' if var in public and not (var == 'authRouter' and 'authenticate' in head) else 'auth'
        rows.append((mounts[var] + (path if path != '/' else ''), method.upper(), auth, ', '.join(f'`{a}:{b}`' for a, b in perms) or ('—' if auth == 'public' else 'any signed-in user')))
res = json.loads(subprocess.check_output(['npx','tsx','-e',"import {resources} from './apps/api/src/crud/registry'; console.log(JSON.stringify(resources.map(r=>({key:r.key,module:r.module,disable:r.disable||[],filters:r.filters||[],search:r.search||[],sensitive:r.sensitive||[],entity:!!r.entityScoped}))))"], cwd=root, env={**__import__('os').environ,'LOG_LEVEL':'silent'}).decode().strip().splitlines()[-1])
out = ['# API reference', '', '_Generated by `scripts/gen-api-docs.py` from the route files and CRUD registry — do not edit by hand._', '',
 'Base URL `/api`. JSON in/out. Authenticated calls send `Authorization: Bearer <access token>`; multi-entity users may send `X-Entity-Id` (omit or `all` for consolidated). Errors: `{ "error": { "message", "code", "details" } }` (400 validation with per-field `details`, 401, 403, 404, 409 conflict/state, 429).', '',
 'Lists accept `?search=&page=&pageSize=&sort=col:asc|desc&from=&to=` plus the resource\'s filter columns (comma-separate for multiple values) and return `{ data, total, page, pageSize }`.', '',
 '## Generic resources (CRUD)', '', 'Permission per verb: `GET` → `<module>:r`, `POST` → `c`, `PATCH` → `u`, `DELETE` → `d`. Columns marked *cost-gated* are removed from responses for users without `costs:r`.', '',
 '| Path | Module | Verbs | Filters | Searches | Cost-gated | Entity-scoped |', '|---|---|---|---|---|---|---|']
for r in res:
    verbs = ['GET (list, by id)'] + [v for v,k in (('POST','create'),('PATCH','update'),('DELETE','delete')) if k not in r['disable']]
    out.append(f"| `/api/{r['key']}` | {r['module']} | {', '.join(verbs)} | {', '.join(r['filters']) or '—'} | {', '.join(r['search']) or '—'} | {', '.join(r['sensitive']) or '—'} | {'yes' if r['entity'] else ''} |")
out += ['', '## Workflow & domain endpoints', '', '| Method | Path | Auth | Permission |', '|---|---|---|---|']
for path, method, auth, perm in sorted(set(rows)):
    out.append(f'| {method} | `{path}` | {auth} | {perm} |')
out += ['', f'_{len(res)} generic resources, {len(set(rows))} workflow endpoints._', '', '## WebSocket', '', '`/ws?token=<access token>` — tenant-scoped domain events (`shipment.status_changed`, `pod.received`, `invoice.paid`, `notification.created`, …). Customer-portal sockets receive only events for their own customer; driver sockets only `trip.*`.']
(root/'docs/API.md').write_text('\n'.join(out) + '\n')
print('wrote docs/API.md:', len(res), 'resources,', len(set(rows)), 'endpoints')
