import { useRef, useState } from 'react';
import { useNavigate, useParams, Link } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, ArrowLeft, CheckCircle2, Copy, Eye, FilePlus2, FileText, Pencil, Plus, Receipt, Trash2, Upload, Download } from 'lucide-react';
import { CHARGE_TYPES, DOC_TYPES, GENERATED_DOC_LABEL, generatedSetFor, modeGroup, type GeneratedDocType } from '@digitalburj/shared';
import { api, openFile } from '../lib/api';
import { useCan } from '../store/session';
import { aed, fdate, fdt, label, pct } from '../lib/format';
import { Badge, Banner, Card, ConfirmModal, DataTable, Detail, Empty, Kpi, Skeleton, StatusBadge, Tabs, Timeline, toast } from '../ui/kit';
import { FormModal, type FieldSpec } from '../ui/forms';

const EDIT_FIELDS: FieldSpec[] = [
  { name: 'carrier', label: 'Carrier' }, { name: 'vessel', label: 'Vessel' }, { name: 'voyage', label: 'Voyage' },
  { name: 'bl_number', label: 'B/L number' }, { name: 'awb_number', label: 'AWB number' }, { name: 'container_no', label: 'Container no.' }, { name: 'container_type', label: 'Equipment' },
  { name: 'pol', label: 'Port of loading' }, { name: 'pod', label: 'Port of discharge' }, { name: 'incoterm', label: 'Incoterm' }, { name: 'hs_code', label: 'HS code' },
  { name: 'pieces', label: 'Pieces', type: 'number' }, { name: 'weight_kg', label: 'Weight (kg)', type: 'number' }, { name: 'volume_cbm', label: 'Volume (CBM)', type: 'number' }, { name: 'cargo_value', label: 'Cargo value (AED)', type: 'number' },
  { name: 'etd', label: 'ETD', type: 'date' }, { name: 'eta', label: 'ETA', type: 'date' }, { name: 'atd', label: 'Actual departure', type: 'date' }, { name: 'ata', label: 'Actual arrival', type: 'date' },
  { name: 'free_days_end', label: 'Free time ends', type: 'datetime', hint: 'Drives demurrage risk alerts' }, { name: 'priority', label: 'Priority', type: 'select', options: ['low', 'normal', 'high', 'urgent'] },
  { name: 'ops_owner_id', label: 'Ops owner', type: 'ref', ref: { resource: 'lookup/users' } },
  { name: 'cargo_description', label: 'Cargo description', type: 'textarea', span: 2 },
];

/** Fields the carrier confirmation must capture, by mode — this is what the generated B/L, AWB or CMR is built from. */
const bookingFields = (mode: string): FieldSpec[] => {
  const g = modeGroup(mode);
  const common: FieldSpec[] = [{ name: 'carrier', label: g === 'Road' ? 'Transporter' : 'Carrier', required: true }];
  const dates: FieldSpec[] = [{ name: 'etd', label: 'ETD', type: 'date' }, { name: 'eta', label: 'ETA', type: 'date' }];
  if (g === 'Sea') return [...common, { name: 'vessel', label: 'Vessel', required: true }, { name: 'voyage', label: 'Voyage' }, { name: 'bl_number', label: 'Master B/L no.' }, { name: 'container_no', label: 'Container no.' }, { name: 'container_type', label: 'Equipment', placeholder: '40HC' }, { name: 'containers', label: 'No. of containers', type: 'number' }, ...dates];
  if (g === 'Air') return [...common, { name: 'voyage', label: 'Flight no.', required: true, placeholder: 'EK 047' }, { name: 'awb_number', label: 'Master AWB no.' }, ...dates];
  return [...common, { name: 'vessel', label: 'Vehicle / plate' }, ...dates];
};
const DOC_ICON_TITLE = 'Generated by the system';

export default function ShipmentDetail() {
  const { id } = useParams();
  const nav = useNavigate();
  const qc = useQueryClient();
  const can = useCan();
  const [tab, setTab] = useState('overview');
  const [editing, setEditing] = useState(false);
  const [booking, setBooking] = useState(false);
  const [chargeOpen, setChargeOpen] = useState(false);
  const [confirmStatus, setConfirmStatus] = useState<string | null>(null);
  const fileRef = useRef<HTMLInputElement>(null);
  const [docType, setDocType] = useState('BL');
  const q = useQuery({ queryKey: ['shipment', id], queryFn: () => api.get(`/shipments/${id}/detail`) });
  const refresh = () => { qc.invalidateQueries({ queryKey: ['shipment', id] }); qc.invalidateQueries({ queryKey: ['res', 'shipments'] }); };
  const status = useMutation({ mutationFn: (s: string) => api.post(`/shipments/${id}/status`, { status: s }), onSuccess: () => { refresh(); toast.success('Status updated'); } });
  const milestone = useMutation({ mutationFn: (v: { mid: string; done: boolean }) => api.patch(`/shipments/${id}/milestones/${v.mid}`, { done: v.done }), onSuccess: refresh });
  const delCharge = useMutation({ mutationFn: (cid: string) => api.del(`/shipments/${id}/charges/${cid}`), onSuccess: () => { refresh(); toast.success('Charge removed'); } });
  const invoice = useMutation({ mutationFn: () => api.post(`/invoices/from-shipment/${id}`, {}), onSuccess: (inv) => { refresh(); toast.success(`Draft ${inv.number} created`); nav('/invoices'); } });
  const upload = useMutation({
    mutationFn: async (file: File) => { const f = new FormData(); f.append('file', file); f.append('shipment_id', id!); f.append('type', docType); return api.upload('/documents/upload', f); },
    onSuccess: () => { refresh(); toast.success('Document uploaded'); },
  });
  const generate = useMutation({
    mutationFn: (types?: GeneratedDocType[]) => api.post(`/shipments/${id}/generate-documents`, types ? { types } : {}),
    onSuccess: (r: any) => { refresh(); toast.success(r.documents.length ? `${r.documents.length} document(s) generated` : 'Nothing to generate'); },
  });
  const togglePublic = useMutation({ mutationFn: (d: any) => api.patch(`/documents/${d.id}`, { is_public: !d.is_public }), onSuccess: refresh });

  if (q.isLoading) return <Skeleton rows={8} />;
  if (q.error || !q.data) return <Empty title="Shipment not found" action={<Link to="/shipments" className="btn outline">Back to shipments</Link>} />;
  const { shipment: s, milestones, charges, documents, customs, stops, invoices, timeline, financials, nextStatuses } = q.data;
  const canCost = can('costs', 'r');
  const trackUrl = `${location.origin}/track/${s.tracking_token || ''}`;
  const unbilled = (charges as any[]).filter((c) => c.kind === 'revenue' && !c.invoice_id);

  return (
    <>
      <div className="page-head">
        <div>
          <Link to="/shipments" className="muted" style={{ fontSize: 12.5, display: 'inline-flex', gap: 4, alignItems: 'center' }}><ArrowLeft size={13} /> Shipments</Link>
          <h1 className="page-title mono" style={{ display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap' }}>{s.number} <StatusBadge value={s.status} />
            {s.risk_level !== 'low' && <Badge tone={s.risk_level === 'high' ? 'bad' : 'warn'}>{label(s.risk_level)} risk</Badge>}</h1>
          <p className="page-sub">{s.customer_name} · {label(s.mode)} · {s.origin || '?'} → {s.destination || '?'}{s.container_no ? ` · ${s.container_no}` : ''}</p>
        </div>
        <div className="actions">
          {can('shipments', 'u') && (nextStatuses as string[]).filter((n) => !(s.status === 'booked' && n === 'confirmed')).map((n) => (
            <button key={n} className={`btn ${n === 'cancelled' ? 'outline' : 'primary'}`} disabled={status.isPending} onClick={() => (n === 'cancelled' ? setConfirmStatus(n) : status.mutate(n))}>
              {n === 'cancelled' ? 'Cancel job' : `Mark ${label(n).toLowerCase()}`}
            </button>
          ))}
          {can('shipments', 'u') && s.status === 'booked' && <button className="btn primary" onClick={() => setBooking(true)}><CheckCircle2 /> Confirm booking</button>}
          {can('shipments', 'u') && <button className="btn outline" onClick={() => setEditing(true)}><Pencil /> Edit</button>}
          {s.tracking_token && <button className="btn outline" onClick={() => { navigator.clipboard?.writeText(trackUrl); toast.success('Public tracking link copied'); }}><Copy /> Tracking link</button>}
        </div>
      </div>
      {s.risk_level !== 'low' && s.risk_reason && <Banner kind={s.risk_level === 'high' ? 'bad' : 'warn'}><b>{s.risk_reason}</b></Banner>}

      <div className="kpis">
        <Kpi label="ETA" value={fdate(s.eta)} sub={s.ata ? `Arrived ${fdate(s.ata)}` : s.etd ? `ETD ${fdate(s.etd)}` : undefined} />
        <Kpi label="Revenue" value={aed(financials.revenue, { compact: true })} sub={`${unbilled.length} unbilled line(s)`} />
        {canCost && <Kpi label="Cost" value={aed(financials.cost, { compact: true })} />}
        {canCost && <Kpi label="Margin" value={aed(financials.margin, { compact: true })} sub={pct(financials.marginPct)} tone={financials.margin >= 0 ? 'up' : 'down'} />}
        <Kpi label="Milestones" value={`${(milestones as any[]).filter((m) => m.status === 'done').length}/${milestones.length}`} />
      </div>

      <Tabs value={tab} onChange={setTab} tabs={[
        { key: 'overview', label: 'Overview' }, { key: 'milestones', label: 'Milestones' }, { key: 'charges', label: 'Charges & P&L', badge: charges.length },
        { key: 'documents', label: 'Documents', badge: documents.length }, { key: 'customs', label: 'Customs', badge: customs.length }, { key: 'transport', label: 'Transport', badge: stops.length },
        { key: 'invoices', label: 'Invoices', badge: invoices.length }, { key: 'activity', label: 'Activity' },
      ]} />

      {tab === 'overview' && (
        <div className="grid g2">
          <Card title="Cargo & carriage"><Detail items={[
            ['Carrier', s.carrier], ['Vessel / voyage', [s.vessel, s.voyage].filter(Boolean).join(' / ') || null], ['B/L', s.bl_number], ['AWB', s.awb_number], ['Container', s.container_no], ['Equipment', s.container_type],
            ['Incoterm', s.incoterm], ['HS code', s.hs_code], ['Pieces', s.pieces], ['Weight', s.weight_kg ? `${s.weight_kg} kg` : null], ['Volume', s.volume_cbm ? `${s.volume_cbm} CBM` : null], ['Cargo value', s.cargo_value ? aed(s.cargo_value) : null],
          ]} /></Card>
          <Card title="Schedule & parties"><Detail items={[
            ['Customer', s.customer_name], ['Consignee', s.consignee_name], ['ETD', fdate(s.etd)], ['ETA', fdate(s.eta)], ['Actual departure', fdate(s.atd)], ['Actual arrival', fdate(s.ata)],
            ['Free time ends', fdt(s.free_days_end)], ['Priority', <StatusBadge key="p" value={s.priority} />], ['Delivered', fdt(s.delivered_at)], ['Created', fdt(s.created_at)],
          ]} /></Card>
          <Card title="Cargo description" className="g2-span"><p>{s.cargo_description || <span className="muted">No description yet — use AI Doc Intel to extract it from the B/L.</span>}</p></Card>
        </div>
      )}

      {tab === 'milestones' && (
        <Card title="Milestones">
          <Timeline items={(milestones as any[]).map((m) => ({
            state: m.status === 'done' ? 'done' : m.status === 'at_risk' || m.status === 'blocked' || (m.due_at && new Date(m.due_at) < new Date() && m.status !== 'done') ? 'bad' : '',
            title: <span style={{ display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap' }}>{m.name}
              {can('shipments', 'u') && <button className="btn xs outline" onClick={() => milestone.mutate({ mid: m.id, done: m.status !== 'done' })}>{m.status === 'done' ? 'Reopen' : 'Mark done'}</button>}</span>,
            sub: m.done_at ? `Done ${fdt(m.done_at)}` : `Due ${fdate(m.due_at)}`,
          }))} />
        </Card>
      )}

      {tab === 'charges' && (
        <Card title="Revenue & cost lines" pad={false} actions={<>
          {can('shipments', 'u') && <button className="btn sm outline" onClick={() => setChargeOpen(true)}><Plus /> Add charge</button>}
          {can('invoices', 'c') && unbilled.length > 0 && <button className="btn sm primary" disabled={invoice.isPending} onClick={() => invoice.mutate()}><Receipt /> Invoice {unbilled.length} line(s)</button>}
        </>}>
          <DataTable rows={charges} empty={<Empty title="No charges yet" text="Accepted quotes copy their lines here automatically." />} columns={[
            { key: 'kind', label: 'Type', render: (c) => <Badge tone={c.kind === 'revenue' ? 'ok' : 'warn'}>{c.kind}</Badge> },
            { key: 'description', label: 'Description', render: (c) => <span><b>{c.description}</b> <span className="muted">· {label(c.charge_type)}{c.supplier_name ? ` · ${c.supplier_name}` : ''}</span></span> },
            { key: 'tax_code', label: 'VAT', render: (c) => <span className="mono">{c.tax_code}</span> },
            { key: 'amount_aed', label: 'Amount (AED)', num: true, render: (c) => aed(c.amount_aed, { noSymbol: true }) },
            { key: 'status', label: 'Status', render: (c) => <StatusBadge value={c.status} /> },
            { key: '_', label: '', sortable: false, render: (c) => (!c.invoice_id && !c.bill_id && can('shipments', 'u') ? <button className="icon-btn" aria-label="Delete charge" onClick={() => delCharge.mutate(c.id)}><Trash2 /></button> : null) },
          ]} />
        </Card>
      )}

      {tab === 'documents' && (
        <Card title="Documents" actions={<>
          {can('shipments', 'u') && <button className="btn sm outline" disabled={generate.isPending} onClick={() => generate.mutate(undefined)} title={`Creates a new version of: ${generatedSetFor(s.mode).map((t) => GENERATED_DOC_LABEL[t]).join(', ')}`}><FilePlus2 /> {generate.isPending ? 'Generating…' : 'Generate documents'}</button>}
          {can('documents', 'c') && <>
          <select className="select" style={{ width: 170, height: 32 }} value={docType} onChange={(e) => setDocType(e.target.value)} aria-label="Document type">{DOC_TYPES.map((d) => <option key={d}>{d}</option>)}</select>
          <input ref={fileRef} type="file" hidden accept=".pdf,.png,.jpg,.jpeg,.webp,.txt,.csv,.docx,.xlsx" onChange={(e) => { const f = e.target.files?.[0]; if (f) upload.mutate(f); e.target.value = ''; }} />
          <button className="btn sm primary" disabled={upload.isPending} onClick={() => fileRef.current?.click()}><Upload /> {upload.isPending ? 'Uploading…' : 'Upload'}</button>
        </>}
        </>}>
          {!documents.length ? <Empty title="No documents" text="Confirm the booking to generate the transport document, packing list and commercial invoice, or upload the originals. POD photos land here automatically." /> : documents.map((d: any) => (
            <div className="list-item" key={d.id}>
              <span className="ico"><FileText /></span>
              <div style={{ flex: 1 }}><b>{d.name}</b> {d.origin === 'generated' && <Badge tone="info">generated v{d.version}</Badge>}<div className="muted" style={{ fontSize: 12 }}>{d.type}{d.doc_no ? ` · ${d.doc_no}` : ''} · {fdt(d.generated_at || d.created_at)}{d.size ? ` · ${(d.size / 1024).toFixed(0)} KB` : ''}</div></div>
              {can('documents', 'u') && <label className="check" title="Visible to the customer in their portal"><input type="checkbox" checked={d.is_public} onChange={() => togglePublic.mutate(d)} /> Portal</label>}
              {d.origin === 'generated'
                ? <button className="btn xs outline" title={DOC_ICON_TITLE} onClick={() => openFile(`/documents/${d.id}/render`).catch((e) => toast.error(e.message))}><Eye /> View</button>
                : <button className="btn xs outline" onClick={() => openFile(`/documents/${d.id}/download`).catch((e) => toast.error(e.message))}><Download /> Open</button>}
            </div>
          ))}
        </Card>
      )}

      {tab === 'customs' && (
        <Card title="Customs declarations" pad={false} actions={<Link className="btn sm outline" to="/customs">Open customs desk</Link>}>
          <DataTable rows={customs} empty={<Empty title="No declaration yet" text="A declaration shell is created automatically when the job enters customs." />} columns={[
            { key: 'number', label: 'Declaration', render: (c) => <b className="mono">{c.number}</b> }, { key: 'type', label: 'Type', render: (c) => label(c.type) }, { key: 'hs_code', label: 'HS', render: (c) => <span className="mono">{c.hs_code || '—'}</span> },
            { key: 'cif_value', label: 'CIF', num: true, render: (c) => aed(c.cif_value, { noSymbol: true }) }, { key: 'duty_amount', label: 'Duty', num: true, render: (c) => aed(c.duty_amount, { noSymbol: true }) },
            { key: 'status', label: 'Status', render: (c) => <span><StatusBadge value={c.status} />{c.hold_reason && <span className="muted"> {c.hold_reason}</span>}</span> },
          ]} />
        </Card>
      )}

      {tab === 'transport' && (
        <Card title="Trips & proof of delivery" pad={false}>
          <DataTable rows={stops} empty={<Empty title="No trip planned" text="Assign this job on the dispatch board." />} columns={[
            { key: 'trip_number', label: 'Trip', render: (r) => <b className="mono">{r.trip_number}</b> }, { key: 'kind', label: 'Stop', render: (r) => label(r.kind) }, { key: 'address', label: 'Address' },
            { key: 'driver_name', label: 'Driver' }, { key: 'status', label: 'Status', render: (r) => <StatusBadge value={r.status} /> }, { key: 'completed_at', label: 'Completed', render: (r) => fdt(r.completed_at) },
          ]} />
        </Card>
      )}

      {tab === 'invoices' && (
        <Card title="Invoices" pad={false}>
          <DataTable rows={invoices} empty={<Empty title="Not invoiced yet" />} columns={[
            { key: 'number', label: 'Invoice', render: (r) => <b className="mono">{r.number}</b> }, { key: 'status', label: 'Status', render: (r) => <StatusBadge value={r.status} /> },
            { key: 'total', label: 'Total', num: true, render: (r) => aed(r.total, { noSymbol: true }) }, { key: 'paid', label: 'Paid', num: true, render: (r) => aed(r.paid, { noSymbol: true }) }, { key: 'due_date', label: 'Due', render: (r) => fdate(r.due_date) },
          ]} />
        </Card>
      )}

      {tab === 'activity' && (
        <Card title="Activity">
          {!timeline.length ? <Empty title="No activity recorded" /> : timeline.map((a: any, i: number) => (
            <div className="list-item" key={i}><span className="ico"><AlertTriangle /></span><div style={{ flex: 1 }}><b>{a.user_name || 'System'}</b> · {label(a.action)}<div className="muted mono" style={{ fontSize: 11.5 }}>{a.changes ? JSON.stringify(a.changes).slice(0, 140) : ''}</div></div><span className="muted">{fdt(a.created_at)}</span></div>
          ))}
        </Card>
      )}

      {booking && (
        <FormModal title={`Confirm booking · ${s.number}`} sub={`Records the ${label(s.mode).toLowerCase()} booking, moves the job to Confirmed and generates ${generatedSetFor(s.mode).map((t) => GENERATED_DOC_LABEL[t]).join(', ')}.`} size="lg" submitLabel="Confirm booking"
          fields={bookingFields(s.mode)} initial={{ carrier: s.carrier, vessel: s.vessel, voyage: s.voyage, bl_number: s.bl_number, awb_number: s.awb_number, container_no: s.container_no, container_type: s.container_type, containers: s.containers, etd: s.etd?.slice(0, 10), eta: s.eta?.slice(0, 10) }}
          onSubmit={async (v) => {
            const body = Object.fromEntries(Object.entries(v).filter(([, x]) => x !== '' && x !== null && x !== undefined));
            const r: any = await api.post(`/shipments/${id}/confirm-booking`, body);
            refresh(); setTab('documents');
            toast.success(r.documents.length ? `Booking confirmed · ${r.documents.length} documents generated` : 'Booking confirmed');
          }} onClose={() => setBooking(false)} />
      )}
      {editing && <FormModal title={`Edit ${s.number}`} size="lg" fields={EDIT_FIELDS} initial={{ ...s }} onSubmit={async (v) => { await api.patch(`/shipments/${id}`, v); refresh(); toast.success('Shipment updated'); }} onClose={() => setEditing(false)} />}
      {chargeOpen && (
        <FormModal title="Add charge" initial={{ kind: 'revenue', charge_type: 'freight', quantity: 1, currency: 'AED', fx_rate: 1 }}
          fields={[
            { name: 'kind', label: 'Kind', type: 'select', required: true, options: canCost ? ['revenue', 'cost'] : ['revenue'] },
            { name: 'charge_type', label: 'Charge type', type: 'select', options: CHARGE_TYPES as unknown as string[] },
            { name: 'description', label: 'Description', required: true, span: 2 },
            { name: 'supplier_id', label: 'Supplier', type: 'ref', ref: { resource: 'suppliers' }, showIf: (v) => v.kind === 'cost' },
            { name: 'quantity', label: 'Quantity', type: 'number', required: true }, { name: 'unit_amount', label: 'Unit amount', type: 'number', required: true },
            { name: 'currency', label: 'Currency', type: 'select', options: ['AED', 'USD', 'EUR', 'GBP', 'CNY', 'INR'] }, { name: 'fx_rate', label: 'FX rate to AED', type: 'number', showIf: (v) => v.currency && v.currency !== 'AED' },
          ]}
          onSubmit={async (v) => { await api.post(`/shipments/${id}/charges`, v); refresh(); toast.success('Charge added'); }} onClose={() => setChargeOpen(false)} />
      )}
      {confirmStatus && <ConfirmModal danger title="Cancel this job?" text="Cancelling is final. Charges stay for audit but the job leaves all active queues." confirmLabel="Cancel job" onConfirm={() => status.mutateAsync(confirmStatus)} onClose={() => setConfirmStatus(null)} />}
    </>
  );
}
